const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {chromium}=require('C:/Users/86177/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const bridge=html.slice(html.indexOf('  // 照片流只读取现有资料'),html.indexOf("  document.addEventListener('click',event=>{if(event.target.closest('#memoryShelfBtn'))"));
const fixture=`<!doctype html><body><button id="photoStreamBtn">照片流</button><div id="photoStreamOverlay" hidden><button id="photoStreamClose">关闭</button><div id="photoStreamStage" style="height:760px"></div></div><script>
const $=id=>document.getElementById(id), appStartPromise=Promise.resolve();
const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const ctx=canvas.getContext('2d');
let records=Array.from({length:51},(_,i)=>{ctx.fillStyle='hsl('+i*7+',70%,55%)';ctx.fillRect(0,0,32,32);return {id:i,cityKey:'city-1',cityName:'孝感市',name:'照片 '+i,dataUrl:canvas.toDataURL(),order:i};});
const extra={dataUrl:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="red"/></svg>'),name:'景点照片'};
const getAllPhotos=async()=>records,getAllCityMeta=async()=>[{cityKey:'city-1',coverImage:records.find(p=>p.kind!=='video')?.dataUrl,attractions:[{name:'景点',photos:[records[0],extra],notes:'真实笔记',visitDate:'2026-09-01'}]}];
let provinceBooks={};
const memoryProvinceBookSettings=()=>provinceBooks;
const cityPoints=[{cityKey:'city-1',name:'孝感市'}],getVisitMonths=()=>[],downloadCloudImage=async path=>{if(path==='saved-cloud-photo')return extra.dataUrl;throw Error('测试下载失败');};
${bridge}</script></body>`;
const server=http.createServer((req,res)=>{
  if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(fixture);}
  const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));
  if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end();}
  fs.readFile(file,(err,data)=>{if(err){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});
});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  try{
    const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto('http://127.0.0.1:'+server.address().port);
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    const frame=()=>page.frames().find(frame=>frame.url().includes('/assets/photo-stream/'));
    await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow.__undertow,{},{timeout:45000});
    assert.equal(await frame().locator('#batch-count').textContent(),'1–48 / 52 张');
    assert.equal(await frame().locator('.directory-grid button').count(),48);
    const coverage=await frame().evaluate(()=>new Set(window.__undertow.stories.flatMap(s=>s.chapters.map(c=>c.photo))).size);
    assert.equal(coverage,48,'每张照片均可从光线故事访问');
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.length),6,'48张照片只使用6条真实照片流');
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.flatMap(s=>s.chapters).length),48,'照片故事不重复复制');
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.every(s=>s.id.startsWith('travel-'))),true,'所有故事均来自用户照片');
    await page.screenshot({path:path.join(require('node:os').tmpdir(),'travel-photo-stream-desktop.png')});
    await frame().locator('#directory-toggle').click();
    await frame().locator('.directory-grid button').first().click();
    await frame().locator('#story').waitFor({state:'visible'});
    assert.equal(await frame().locator('#story-title').textContent(),'孝感市');
    await frame().locator('#story.unfolded').waitFor();
    await frame().waitForFunction(()=>[...document.querySelectorAll('.shot')].some(shot=>{const r=shot.getBoundingClientRect();return r.top>70&&r.bottom<innerHeight-50;}));
    const visibleShot=await frame().evaluate(()=>[...document.querySelectorAll('.shot')].findIndex(shot=>{const r=shot.getBoundingClientRect();return r.top>70&&r.bottom<innerHeight-50;}));
    assert.ok(visibleShot>=0,'展开后有可点击的照片');
    await frame().locator('.shot').nth(visibleShot).click();
    await frame().locator('.lightbox').waitFor({state:'visible'});
    await frame().locator('.lightbox').click();
    await frame().locator('.story-back').click();
    await frame().locator('#story').waitFor({state:'hidden'});
    await frame().locator('#batch-next').click();
    await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow.__undertow&&document.querySelector('iframe').contentDocument.querySelector('#batch-count').textContent==='49–52 / 52 张',{},{timeout:45000});
    assert.equal(await frame().locator('.directory-grid button').count(),4);
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.length),1,'尾批四张只使用一条照片流');
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.flatMap(s=>s.chapters).length),4);
    assert.equal(await frame().locator('#batch-next').isDisabled(),true);
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.some(s=>s.chapters.some(c=>c.text==='真实笔记'&&c.date==='2026-09-01'))),true);
    await frame().locator('#batch-prev').click();
    await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow.__undertow&&document.querySelector('iframe').contentDocument.querySelector('#batch-count').textContent==='1–48 / 52 张',{},{timeout:45000});
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    assert.equal(await page.locator('iframe').count(),0,'关闭后销毁渲染器');
    await page.evaluate(()=>{records=[{id:100,kind:'video',dataUrl:'data:video/mp4;base64,AAA'},{...records[1],id:101}];});
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    const batch=await page.evaluate(()=>window.TravelPhotoStreamBridge.readBatch());
    assert.equal(batch.total,2,'视频排除，城市封面去重，景点照片保留');
    assert.equal(errors.length,0,errors.join('\n'));
    console.log('PASS: 52张照片完整覆盖、48张分批、光瀑渲染、目录定位、放大、真实笔记、去重、排除视频、关闭释放');
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow.__undertow,{},{timeout:45000});
    const overflow=await frame().evaluate(()=>document.querySelector('.stream-toolbar').getBoundingClientRect().right>innerWidth);
    assert.equal(overflow,false,'手机工具栏不超出屏幕');
    console.log('PASS: 手机尺寸正常渲染，工具栏无横向溢出');
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.evaluate(()=>{
      const coverCanvas=document.createElement('canvas');coverCanvas.width=coverCanvas.height=19;
      provinceBooks={'湖北省':{cover:coverCanvas.toDataURL(),review:'用户封面寄语'}};
      records=[{...records[1],id:500},{id:500,cityKey:'city-1',storagePath:'saved-cloud-photo',name:'云端照片'}];
    });
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    const sources=await page.evaluate(()=>window.TravelPhotoStreamBridge.readBatch());
    assert.equal(sources.total,4,'不同照片同ID不丢失，包含景点与省份封面');
    assert.ok(sources.photos.some(p=>p.description.includes('云端照片')&&p.src.startsWith('data:image/')));
    assert.ok(sources.photos.some(p=>p.description.includes('省份书籍封面')&&p.text==='用户封面寄语'&&p.date===''));
    console.log('PASS: 城市、景点、城市封面、省份封面及云端存储来源完整，去重不误删同ID照片');
    const fallback=await browser.newPage();
    await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl2'?null:original.call(this,type,...args);};});
    await fallback.goto('http://127.0.0.1:'+server.address().port);
    await fallback.getByRole('button',{name:'照片流',exact:true}).click();
    await fallback.frameLocator('iframe').locator('#photo-directory').waitFor({state:'visible'});
    await fallback.frameLocator('iframe').locator('.directory-grid button').first().click();
    await fallback.frameLocator('iframe').locator('#fallback-preview').waitFor({state:'visible'});
    console.log('PASS: 不支持WebGL的设备可通过目录查看原图');
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
