const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {chromium}=require('C:/Users/86177/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const bridge=html.slice(html.indexOf('  // 照片流只读取现有资料'),html.indexOf("  document.addEventListener('click',event=>{if(event.target.closest('#memoryShelfBtn'))"));
const fixture=`<!doctype html><body><button id="photoStreamBtn">照片流</button><div id="photoStreamOverlay" hidden><button id="photoStreamClose">关闭</button><div id="photoStreamStage" style="height:760px"></div></div><script>
const $=id=>document.getElementById(id), appStartPromise=Promise.resolve();
const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const ctx=canvas.getContext('2d');
let records=Array.from({length:51},(_,i)=>{ctx.fillStyle='hsl('+i*7+',70%,55%)';ctx.fillRect(0,0,32,32);return {id:i,cityKey:'city-1',cityName:'孝感市',name:'照片 '+i,dataUrl:canvas.toDataURL(),order:i};});
const extra={dataUrl:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="red"/></svg>'),name:'景点照片'};
const getAllPhotos=async()=>records,getAllCityMeta=async()=>supplemental?[{cityKey:'city-1',coverImage:records.find(p=>p.kind!=='video')?.dataUrl,attractions:[{name:'景点',photos:[records[0],extra],notes:'真实笔记',visitDate:'2026-09-01'}]}]:[];
let provinceBooks={},supplemental=true;
const memoryProvinceBookSettings=()=>provinceBooks;
const cityPoints=[{cityKey:'city-1',name:'孝感市'}],getVisitMonths=()=>[],downloadCloudImage=async path=>{if(path==='saved-cloud-photo')return extra.dataUrl;throw Error('测试下载失败');};
${bridge}</script></body>`;
const server=http.createServer((req,res)=>{
  if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(fixture);}
  const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));
  if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end();}
  fs.readFile(file,(err,data)=>{if(err){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});
});
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  try{
    const page=await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:2,reducedMotion:'reduce'});
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto('http://127.0.0.1:'+server.address().port);
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    const frame=()=>page.frames().find(frame=>frame.url().includes('/assets/photo-stream/'));
    const ready=()=>page.waitForFunction(()=>document.querySelector('iframe')?.contentWindow.__undertow,{},{timeout:45000});
    await ready();
    assert.ok(await frame().evaluate(()=>{const canvas=document.querySelector('#stream');return canvas.width*canvas.height<=1503000;}),'高分屏光效画布应限制像素开销');
    const idleLabelMutations=await frame().evaluate(async()=>{
      const {cam,LS_MIN}=window.__undertow;
      cam.x=0;cam.y=6.4;cam.vx=cam.vy=0;cam.ls=cam.lsT=LS_MIN();
      await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
      let mutations=0;
      const observer=new MutationObserver(records=>{mutations+=records.length;});
      observer.observe(document.querySelector('#city-labels'),{subtree:true,attributes:true});
      for(let i=0;i<8;i++)await new Promise(resolve=>requestAnimationFrame(resolve));
      observer.disconnect();return mutations;
    });
    assert.equal(idleLabelMutations,0,'镜头不动时不应反复写入城市名称样式');
    await frame().evaluate(()=>window.__undertow.zoomBy(.8,640,380));
    await frame().waitForFunction(()=>Math.abs(window.__undertow.cam.ls-window.__undertow.cam.lsT)<.01);
    const beforeDrag=await frame().evaluate(()=>({x:window.__undertow.cam.x,y:window.__undertow.cam.y}));
    await page.mouse.move(640,400);await page.mouse.down();
    await page.mouse.move(730,430,{steps:8});await page.mouse.up();
    await frame().waitForFunction(({x,y})=>Math.hypot(window.__undertow.cam.x-x,window.__undertow.cam.y-y)>.05,beforeDrag);
    await frame().waitForFunction(()=>{const rect=document.querySelector('#city-labels span').getBoundingClientRect();return Math.abs(rect.x+rect.width/2-window.__undertow.project(window.__undertow.fib.x0[0],15).x)<2;});
    console.log('PASS: 高分屏渲染像素预算、静止标签零重复更新、缩放拖动与名称对齐');
    assert.equal(await frame().locator('#photo-count').textContent(),'1 座城市 · 51 张照片');
    assert.equal(await frame().locator('.directory-grid button').count(),51);
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.length),1,'一座城市只有一条光线');
    assert.equal(await frame().locator('#city-labels span').textContent(),'孝感市','光线顶部显示真实城市名');
    assert.equal(await frame().evaluate(()=>window.__undertow.stories[0].chapters.length),51,'单城超过8/48张不截断');
    assert.equal(await frame().locator('#batch-next').count(),0,'取消批次切换');
    await page.screenshot({path:path.join(require('node:os').tmpdir(),'travel-photo-stream-desktop.png')});
    await frame().locator('#directory-toggle').click();
    await frame().locator('.directory-grid button').first().click();
    await frame().locator('#story.unfolded').waitFor();
    assert.equal(await frame().locator('#story-title').textContent(),'孝感市');
    await frame().waitForFunction(()=>[...document.querySelectorAll('.shot')].some(shot=>{const r=shot.getBoundingClientRect();return r.top>70&&r.bottom<innerHeight-50;}));
    const visibleShot=await frame().evaluate(()=>[...document.querySelectorAll('.shot')].findIndex(shot=>{const r=shot.getBoundingClientRect();return r.top>70&&r.bottom<innerHeight-50;}));
    await frame().locator('.shot').nth(visibleShot).click();
    await frame().locator('.lightbox').waitFor({state:'visible'});
    await frame().locator('.lightbox').click();
    await frame().locator('.story-back').click();
    await frame().locator('#story').waitFor({state:'hidden'});
    await frame().locator('#directory-toggle').click();
    await frame().locator('.directory-grid button').last().click();
    await frame().locator('#story.unfolded').waitFor();
    await frame().waitForFunction(()=>[...document.querySelectorAll('.shot[data-i="50"]')].some(shot=>{const r=shot.getBoundingClientRect();return r.top>0&&r.bottom<innerHeight;}));
    assert.equal(await frame().evaluate(()=>window.__undertow.stories[0].chapters[50].text),'');
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    assert.equal(await page.locator('iframe').count(),0,'关闭后销毁渲染器');
    console.log('PASS: 一城一线、51张相册照片完整覆盖、不额外加入景点照片和封面、目录定位最后一张、原图放大、关闭释放');
    await page.evaluate(()=>{records=[{id:100,kind:'video',dataUrl:'data:video/mp4;base64,AAA'},{...records[1],id:101}];});
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    const catalog=await page.evaluate(()=>window.TravelPhotoStreamBridge.readCatalog());
    assert.equal(catalog.total,1,'仅导入城市相册图片，排除视频和额外景点照片');
    await ready();
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    await ready();
    assert.equal(await frame().evaluate(()=>document.querySelector('.stream-toolbar').getBoundingClientRect().right>innerWidth),false);
    console.log('PASS: 手机光瀑渲染及工具栏无溢出');
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.evaluate(()=>{
      const coverCanvas=document.createElement('canvas');coverCanvas.width=coverCanvas.height=19;
      provinceBooks={'湖北省':{cover:coverCanvas.toDataURL(),review:'用户封面寄语'}};
      records=[{...records[1],id:500},{id:500,cityKey:'city-1',storagePath:'saved-cloud-photo',name:'云端照片'}];
    });
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    const sources=await page.evaluate(()=>window.TravelPhotoStreamBridge.readCatalog());
    assert.equal(sources.total,2,'不同照片同ID不丢失，不混入独立封面和景点照片');
    assert.ok(sources.photos.some(p=>p.description.includes('云端照片')&&p.src.startsWith('data:image/')));
    assert.ok(sources.photos.every(p=>p.cityKey==='city-1'));
    console.log('PASS: 仅使用主页相册数据，云端照片正常读取');
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.evaluate(()=>{supplemental=false;const src=records.find(photo=>photo.dataUrl).dataUrl;records=Array.from({length:60},(_,i)=>({id:i,cityKey:'city-'+i,cityName:'城市'+i,dataUrl:src}));});
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    await ready();
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.length),60);
    assert.equal(await frame().evaluate(()=>window.__undertow.fib.x0.length),60,'光线状态按实际城市数分配');
    assert.equal(await frame().locator('#city-labels span').count(),60,'每条城市光线对应一个名称');
    assert.equal(await frame().locator('#city-labels span').last().textContent(),'城市59');
    await frame().waitForFunction(()=>{
      const label=document.querySelector('#city-labels span:last-child');
      const rect=label.getBoundingClientRect();
      return Math.abs(rect.x+rect.width/2-window.__undertow.project(window.__undertow.fib.x0[59],15).x)<2;
    });
    assert.equal(await frame().evaluate(()=>window.__undertow.stories.every(s=>s.chapters.length===1)),true);
    await frame().locator('#directory-toggle').click();
    await frame().locator('.directory-grid button').last().click();
    await frame().locator('#story.unfolded').waitFor();
    assert.equal(await frame().locator('#story-title').textContent(),'城市59');
    assert.equal(errors.length,0,errors.join('\n'));
    console.log('PASS: 60座城市生成60条光线、跨城市同图保留、目录定位正确城市');
    await page.getByRole('button',{name:'关闭',exact:true}).click();
    await page.evaluate(()=>{supplemental=true;const src=records[0].dataUrl;records=Array.from({length:159},(_,i)=>({id:i,cityKey:'city-1',cityName:'孝感市',dataUrl:src}));});
    await page.getByRole('button',{name:'照片流',exact:true}).click();
    assert.equal((await page.evaluate(()=>window.TravelPhotoStreamBridge.readCatalog())).total,159,'主页159条相册记录全部保留，不按图片内容去重');
    console.log('PASS: 主页159张对应照片流159张');
    const fallback=await browser.newPage();
    await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl2'?null:original.call(this,type,...args);};});
    await fallback.goto('http://127.0.0.1:'+server.address().port);
    await fallback.getByRole('button',{name:'照片流',exact:true}).click();
    await fallback.frameLocator('iframe').locator('#photo-directory').waitFor({state:'visible'});
    await fallback.frameLocator('iframe').locator('.directory-grid button').first().click();
    await fallback.frameLocator('iframe').locator('#fallback-preview').waitFor({state:'visible'});
    console.log('PASS: 无WebGL设备可查看全部照片');
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(error=>{console.error(error);process.exitCode=1;});
